[33mcommit 8972f32ea96ce351c8f2710674f934b5c2af1d0e[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m)[m
Author: Sergey Timofeev <drumliker@yandex.ru>
Date:   Sat Nov 26 13:05:11 2022 +0300

    Создали структуру проекта

[1mdiff --git a/index.html b/index.html[m
[1mnew file mode 100644[m
[1mindex 0000000..56efbdb[m
[1m--- /dev/null[m
[1m+++ b/index.html[m
[36m@@ -0,0 +1,12 @@[m
[32m+[m[32m<!DOCTYPE html>[m
[32m+[m[32m<html lang="en">[m
[32m+[m[32m<head>[m
[32m+[m[32m    <meta charset="UTF-8">[m
[32m+[m[32m    <meta http-equiv="X-UA-Compatible" content="IE=edge">[m
[32m+[m[32m    <meta name="viewport" content="width=device-width, initial-scale=1.0">[m
[32m+[m[32m    <title>Document</title>[m
[32m+[m[32m</head>[m
[32m+[m[32m<body>[m
[32m+[m[41m    [m
[32m+[m[32m</body>[m
[32m+[m[32m</html>[m
\ No newline at end of file[m
[1mdiff --git a/text.txt b/text.txt[m
[1mnew file mode 100644[m
[1mindex 0000000..e69de29[m
